services:
  - type: web
    name: ticket-api
    runtime: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: COUCHBASE_CONN_STRING
        value: couchbases://cb.fig9ra1k4bwds7df.cloud.couchbase.com
      - key: COUCHBASE_USERNAME
        value: admin
      - key: COUCHBASE_PASSWORD
        sync: false
      - key: COUCHBASE_BUCKET
        value: travel-sample
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://ticket-management-system-vpg7.onrender.com,http://localhost:5173
      - key: PORT
        value: 5000
    healthCheckPath: /api/health
